package com.htttdn.hrm.dto.response.common;

public enum ErrorCode {
    // Authentication / account
    USERNAME_TAKEN,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    ACCOUNT_PENDING,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    ACCOUNT_NOT_FOUND,
    EMPLOYEE_ACCOUNT_EXISTS,
    ACCOUNT_PROVISIONING_NOT_ALLOWED,
    ACCOUNT_STATUS_TRANSITION_NOT_ALLOWED,
    UNAUTHORIZED,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    ACTIVATION_TOKEN_INVALID,
    ACTIVATION_TOKEN_EXPIRED,
    ACCOUNT_ACTIVATION_NOT_ALLOWED,

    // Employee
    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_ASSIGNMENT_NOT_FOUND,
    EMPLOYEE_CODE_TAKEN,
    EMPLOYMENT_STATUS_TRANSITION_NOT_ALLOWED,

    // Organization
    ORGANIZATION_UNIT_NOT_FOUND,
    JOB_POSITION_NOT_FOUND,
    LOCATION_NOT_FOUND,
    ORGANIZATION_UNIT_CODE_TAKEN,
    WORK_LOCATION_CODE_TAKEN,
    JOB_POSITION_CODE_TAKEN,
    WORK_SHIFT_NOT_FOUND,
    WORK_SHIFT_CODE_TAKEN,
    WORK_SHIFT_SCHEDULE_INVALID,
    ORGANIZATION_HIERARCHY_INVALID,
    ORGANIZATION_RESOURCE_IN_USE,
    COMPANY_OWNER_ALREADY_EXISTS,

    // Request / leave
    REQUEST_NOT_FOUND,
    REQUEST_ALREADY_PROCESSED,
    INSUFFICIENT_LEAVE_BALANCE,

    // Attendance
    ATTENDANCE_NOT_FOUND,

    // Payroll
    PAYROLL_PERIOD_NOT_FOUND,
    PAYROLL_PERIOD_LOCKED,
    PAYSLIP_NOT_FOUND,

    // Authorization
    ROLE_NOT_FOUND,
    ROLE_ASSIGNMENT_NOT_FOUND,
    ROLE_ASSIGNMENT_EXISTS,
    ROLE_ASSIGNMENT_NOT_ALLOWED,
    ROLE_ASSIGNMENT_REQUEST_NOT_FOUND,
    ROLE_ASSIGNMENT_REQUEST_EXISTS,
    ROLE_ASSIGNMENT_REQUEST_ALREADY_PROCESSED,
    PERMISSION_OVERRIDE_NOT_FOUND,
    PERMISSION_OVERRIDE_EXISTS,
    PERMISSION_OVERRIDE_NOT_ALLOWED,
    PERMISSION_NOT_FOUND,
    FORBIDDEN,

    // Validation
    VALIDATION_ERROR,

    // Generic
    RESOURCE_NOT_FOUND,
    CONFLICT,
    CONCURRENT_MODIFICATION,
    INTERNAL_ERROR
}
